name: flutter_innospace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^9.1.1
  
  provider: ^6.0.5 

  http: ^1.5.0 
  path: ^1.9.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.5 
  image_picker: ^1.2.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
